[2025-01-22T12:02:35.700+0000] {processor.py:186} INFO - Started process (PID=33) to work on /opt/airflow/dags/reddit_dag.py
[2025-01-22T12:02:35.703+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2025-01-22T12:02:35.711+0000] {logging_mixin.py:190} INFO - [2025-01-22T12:02:35.710+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2025-01-22T12:02:35.745+0000] {logging_mixin.py:190} INFO - [2025-01-22T12:02:35.735+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 7, in <module>
    sys.path.insert(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
TypeError: insert expected 2 arguments, got 1
[2025-01-22T12:02:35.747+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2025-01-22T12:02:35.813+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/reddit_dag.py took 0.128 seconds
[2025-01-22T12:03:06.470+0000] {processor.py:186} INFO - Started process (PID=34) to work on /opt/airflow/dags/reddit_dag.py
[2025-01-22T12:03:06.479+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2025-01-22T12:03:06.566+0000] {logging_mixin.py:190} INFO - [2025-01-22T12:03:06.549+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2025-01-22T12:03:06.680+0000] {logging_mixin.py:190} INFO - [2025-01-22T12:03:06.660+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 7, in <module>
    sys.path.insert(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
TypeError: insert expected 2 arguments, got 1
[2025-01-22T12:03:06.684+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2025-01-22T12:03:07.365+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/reddit_dag.py took 1.074 seconds
[2025-01-22T12:04:20.526+0000] {processor.py:186} INFO - Started process (PID=35) to work on /opt/airflow/dags/reddit_dag.py
[2025-01-22T12:04:21.275+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2025-01-22T12:05:28.955+0000] {logging_mixin.py:190} INFO - [2025-01-22T12:05:28.502+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2025-01-22T12:05:59.339+0000] {processor.py:186} INFO - Started process (PID=36) to work on /opt/airflow/dags/reddit_dag.py
[2025-01-22T12:05:59.344+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2025-01-22T12:05:59.373+0000] {logging_mixin.py:190} INFO - [2025-01-22T12:05:59.372+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2025-01-22T12:05:59.418+0000] {logging_mixin.py:190} INFO - [2025-01-22T12:05:59.405+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 7, in <module>
    sys.path.insert(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
TypeError: insert expected 2 arguments, got 1
[2025-01-22T12:05:59.422+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2025-01-22T12:05:59.659+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/reddit_dag.py took 0.400 seconds
[2025-01-22T12:06:41.712+0000] {processor.py:186} INFO - Started process (PID=37) to work on /opt/airflow/dags/reddit_dag.py
[2025-01-22T12:06:41.725+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2025-01-22T12:06:41.749+0000] {logging_mixin.py:190} INFO - [2025-01-22T12:06:41.740+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2025-01-22T12:06:41.788+0000] {logging_mixin.py:190} INFO - [2025-01-22T12:06:41.775+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 7, in <module>
    sys.path.insert(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
TypeError: insert expected 2 arguments, got 1
[2025-01-22T12:06:41.791+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2025-01-22T12:06:41.901+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/reddit_dag.py took 11.143 seconds
[2025-01-22T12:07:12.174+0000] {processor.py:186} INFO - Started process (PID=38) to work on /opt/airflow/dags/reddit_dag.py
[2025-01-22T12:07:12.176+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2025-01-22T12:07:12.187+0000] {logging_mixin.py:190} INFO - [2025-01-22T12:07:12.185+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2025-01-22T12:07:12.203+0000] {logging_mixin.py:190} INFO - [2025-01-22T12:07:12.198+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 7, in <module>
    sys.path.insert(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
TypeError: insert expected 2 arguments, got 1
[2025-01-22T12:07:12.205+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2025-01-22T12:07:12.281+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/reddit_dag.py took 0.130 seconds
[2025-01-22T12:07:42.670+0000] {processor.py:186} INFO - Started process (PID=39) to work on /opt/airflow/dags/reddit_dag.py
[2025-01-22T12:07:42.672+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2025-01-22T12:07:42.682+0000] {logging_mixin.py:190} INFO - [2025-01-22T12:07:42.680+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2025-01-22T12:07:42.696+0000] {logging_mixin.py:190} INFO - [2025-01-22T12:07:42.692+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 7, in <module>
    sys.path.insert(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
TypeError: insert expected 2 arguments, got 1
[2025-01-22T12:07:42.699+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2025-01-22T12:07:42.746+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/reddit_dag.py took 0.096 seconds
[2025-01-22T12:08:13.075+0000] {processor.py:186} INFO - Started process (PID=40) to work on /opt/airflow/dags/reddit_dag.py
[2025-01-22T12:08:13.077+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2025-01-22T12:08:13.108+0000] {logging_mixin.py:190} INFO - [2025-01-22T12:08:13.101+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2025-01-22T12:08:13.134+0000] {logging_mixin.py:190} INFO - [2025-01-22T12:08:13.130+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 7, in <module>
    sys.path.insert(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
TypeError: insert expected 2 arguments, got 1
[2025-01-22T12:08:13.136+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2025-01-22T12:08:13.213+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/reddit_dag.py took 0.168 seconds
[2025-01-22T12:09:34.116+0000] {processor.py:186} INFO - Started process (PID=41) to work on /opt/airflow/dags/reddit_dag.py
[2025-01-22T12:09:34.119+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2025-01-22T12:09:34.134+0000] {logging_mixin.py:190} INFO - [2025-01-22T12:09:34.131+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2025-01-22T12:09:34.169+0000] {logging_mixin.py:190} INFO - [2025-01-22T12:09:34.158+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 7, in <module>
    sys.path.insert(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
TypeError: insert expected 2 arguments, got 1
[2025-01-22T12:09:34.172+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2025-01-22T12:09:34.283+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/reddit_dag.py took 0.245 seconds
[2025-01-22T12:10:04.416+0000] {processor.py:186} INFO - Started process (PID=42) to work on /opt/airflow/dags/reddit_dag.py
[2025-01-22T12:10:04.418+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2025-01-22T12:10:04.426+0000] {logging_mixin.py:190} INFO - [2025-01-22T12:10:04.425+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2025-01-22T12:10:04.439+0000] {logging_mixin.py:190} INFO - [2025-01-22T12:10:04.436+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 7, in <module>
    sys.path.insert(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
TypeError: insert expected 2 arguments, got 1
[2025-01-22T12:10:04.441+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2025-01-22T12:10:04.493+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/reddit_dag.py took 0.094 seconds
[2025-01-22T12:10:34.732+0000] {processor.py:186} INFO - Started process (PID=43) to work on /opt/airflow/dags/reddit_dag.py
[2025-01-22T12:10:34.736+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2025-01-22T12:10:34.746+0000] {logging_mixin.py:190} INFO - [2025-01-22T12:10:34.745+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2025-01-22T12:10:34.765+0000] {logging_mixin.py:190} INFO - [2025-01-22T12:10:34.756+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 7, in <module>
    sys.path.insert(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
TypeError: insert expected 2 arguments, got 1
[2025-01-22T12:10:34.768+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2025-01-22T12:10:34.828+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/reddit_dag.py took 0.122 seconds
[2025-01-22T12:12:00.261+0000] {processor.py:186} INFO - Started process (PID=33) to work on /opt/airflow/dags/reddit_dag.py
[2025-01-22T12:12:00.263+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2025-01-22T12:12:00.272+0000] {logging_mixin.py:190} INFO - [2025-01-22T12:12:00.271+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2025-01-22T12:12:00.283+0000] {logging_mixin.py:190} INFO - [2025-01-22T12:12:00.279+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 7, in <module>
    sys.path.insert(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
TypeError: insert expected 2 arguments, got 1
[2025-01-22T12:12:00.285+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2025-01-22T12:12:00.333+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/reddit_dag.py took 0.091 seconds
[2025-01-22T12:12:30.627+0000] {processor.py:186} INFO - Started process (PID=34) to work on /opt/airflow/dags/reddit_dag.py
[2025-01-22T12:12:30.631+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2025-01-22T12:12:30.641+0000] {logging_mixin.py:190} INFO - [2025-01-22T12:12:30.640+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2025-01-22T12:12:30.652+0000] {logging_mixin.py:190} INFO - [2025-01-22T12:12:30.649+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 7, in <module>
    sys.path.insert(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
TypeError: insert expected 2 arguments, got 1
[2025-01-22T12:12:30.654+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2025-01-22T12:12:30.697+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/reddit_dag.py took 0.087 seconds
[2025-01-22T12:14:09.566+0000] {processor.py:186} INFO - Started process (PID=33) to work on /opt/airflow/dags/reddit_dag.py
[2025-01-22T12:14:09.570+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2025-01-22T12:14:09.577+0000] {logging_mixin.py:190} INFO - [2025-01-22T12:14:09.576+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2025-01-22T12:14:09.592+0000] {logging_mixin.py:190} INFO - [2025-01-22T12:14:09.587+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 7, in <module>
    sys.path.insert(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
TypeError: insert expected 2 arguments, got 1
[2025-01-22T12:14:09.594+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2025-01-22T12:14:09.645+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/reddit_dag.py took 0.097 seconds
[2025-01-22T12:14:40.419+0000] {processor.py:186} INFO - Started process (PID=34) to work on /opt/airflow/dags/reddit_dag.py
[2025-01-22T12:14:40.426+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2025-01-22T12:14:40.513+0000] {logging_mixin.py:190} INFO - [2025-01-22T12:14:40.501+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2025-01-22T12:14:40.595+0000] {logging_mixin.py:190} INFO - [2025-01-22T12:14:40.575+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 7, in <module>
    sys.path.insert(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
TypeError: insert expected 2 arguments, got 1
[2025-01-22T12:14:40.599+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2025-01-22T12:14:40.978+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/reddit_dag.py took 0.718 seconds
[2025-01-22T12:15:11.852+0000] {processor.py:186} INFO - Started process (PID=35) to work on /opt/airflow/dags/reddit_dag.py
[2025-01-22T12:15:11.857+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2025-01-22T12:15:11.891+0000] {logging_mixin.py:190} INFO - [2025-01-22T12:15:11.889+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2025-01-22T12:15:11.914+0000] {logging_mixin.py:190} INFO - [2025-01-22T12:15:11.905+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 7, in <module>
    sys.path.insert(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
TypeError: insert expected 2 arguments, got 1
[2025-01-22T12:15:11.916+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2025-01-22T12:15:12.021+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/reddit_dag.py took 0.239 seconds
[2025-01-22T12:15:42.173+0000] {processor.py:186} INFO - Started process (PID=36) to work on /opt/airflow/dags/reddit_dag.py
[2025-01-22T12:15:42.177+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2025-01-22T12:15:42.188+0000] {logging_mixin.py:190} INFO - [2025-01-22T12:15:42.186+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2025-01-22T12:15:42.199+0000] {logging_mixin.py:190} INFO - [2025-01-22T12:15:42.196+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 7, in <module>
    sys.path.insert(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
TypeError: insert expected 2 arguments, got 1
[2025-01-22T12:15:42.201+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2025-01-22T12:15:42.259+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/reddit_dag.py took 0.103 seconds
[2025-01-22T12:16:12.572+0000] {processor.py:186} INFO - Started process (PID=37) to work on /opt/airflow/dags/reddit_dag.py
[2025-01-22T12:16:12.575+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2025-01-22T12:16:12.590+0000] {logging_mixin.py:190} INFO - [2025-01-22T12:16:12.588+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2025-01-22T12:16:12.629+0000] {logging_mixin.py:190} INFO - [2025-01-22T12:16:12.618+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 7, in <module>
    sys.path.insert(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
TypeError: insert expected 2 arguments, got 1
[2025-01-22T12:16:12.633+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2025-01-22T12:16:12.724+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/reddit_dag.py took 0.178 seconds
[2025-01-22T12:16:43.225+0000] {processor.py:186} INFO - Started process (PID=38) to work on /opt/airflow/dags/reddit_dag.py
[2025-01-22T12:16:43.228+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2025-01-22T12:16:43.267+0000] {logging_mixin.py:190} INFO - [2025-01-22T12:16:43.261+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2025-01-22T12:16:43.376+0000] {logging_mixin.py:190} INFO - [2025-01-22T12:16:43.363+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 7, in <module>
    sys.path.insert(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
TypeError: insert expected 2 arguments, got 1
[2025-01-22T12:16:43.379+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2025-01-22T12:16:43.477+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/reddit_dag.py took 0.302 seconds
[2025-01-22T12:17:25.444+0000] {processor.py:186} INFO - Started process (PID=39) to work on /opt/airflow/dags/reddit_dag.py
[2025-01-22T12:17:25.449+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2025-01-22T12:17:25.469+0000] {logging_mixin.py:190} INFO - [2025-01-22T12:17:25.466+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2025-01-22T12:17:25.527+0000] {logging_mixin.py:190} INFO - [2025-01-22T12:17:25.500+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 7, in <module>
    sys.path.insert(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
TypeError: insert expected 2 arguments, got 1
[2025-01-22T12:17:25.536+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2025-01-22T12:17:25.762+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/reddit_dag.py took 0.372 seconds
[2025-01-22T12:17:56.160+0000] {processor.py:186} INFO - Started process (PID=40) to work on /opt/airflow/dags/reddit_dag.py
[2025-01-22T12:17:56.163+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2025-01-22T12:17:56.177+0000] {logging_mixin.py:190} INFO - [2025-01-22T12:17:56.174+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2025-01-22T12:17:56.200+0000] {logging_mixin.py:190} INFO - [2025-01-22T12:17:56.194+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 7, in <module>
    sys.path.insert(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
TypeError: insert expected 2 arguments, got 1
[2025-01-22T12:17:56.203+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2025-01-22T12:17:56.270+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/reddit_dag.py took 0.135 seconds
[2025-01-22T12:18:26.578+0000] {processor.py:186} INFO - Started process (PID=41) to work on /opt/airflow/dags/reddit_dag.py
[2025-01-22T12:18:26.581+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2025-01-22T12:18:26.590+0000] {logging_mixin.py:190} INFO - [2025-01-22T12:18:26.589+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2025-01-22T12:18:26.602+0000] {logging_mixin.py:190} INFO - [2025-01-22T12:18:26.598+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 7, in <module>
    sys.path.insert(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
TypeError: insert expected 2 arguments, got 1
[2025-01-22T12:18:26.604+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2025-01-22T12:18:26.654+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/reddit_dag.py took 0.096 seconds
[2025-01-22T12:18:57.014+0000] {processor.py:186} INFO - Started process (PID=42) to work on /opt/airflow/dags/reddit_dag.py
[2025-01-22T12:18:57.017+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2025-01-22T12:18:57.026+0000] {logging_mixin.py:190} INFO - [2025-01-22T12:18:57.025+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2025-01-22T12:18:57.041+0000] {logging_mixin.py:190} INFO - [2025-01-22T12:18:57.035+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 7, in <module>
    sys.path.insert(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
TypeError: insert expected 2 arguments, got 1
[2025-01-22T12:18:57.043+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2025-01-22T12:18:57.112+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/reddit_dag.py took 0.120 seconds
[2025-01-22T12:20:40.518+0000] {processor.py:186} INFO - Started process (PID=43) to work on /opt/airflow/dags/reddit_dag.py
[2025-01-22T12:20:40.528+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2025-01-22T12:20:40.553+0000] {logging_mixin.py:190} INFO - [2025-01-22T12:20:40.543+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2025-01-22T12:20:40.624+0000] {logging_mixin.py:190} INFO - [2025-01-22T12:20:40.605+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 7, in <module>
    sys.path.insert(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
TypeError: insert expected 2 arguments, got 1
[2025-01-22T12:20:40.627+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2025-01-22T12:22:37.226+0000] {processor.py:186} INFO - Started process (PID=33) to work on /opt/airflow/dags/reddit_dag.py
[2025-01-22T12:22:37.231+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2025-01-22T12:22:37.239+0000] {logging_mixin.py:190} INFO - [2025-01-22T12:22:37.238+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2025-01-22T12:22:37.256+0000] {logging_mixin.py:190} INFO - [2025-01-22T12:22:37.251+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 7, in <module>
    sys.path.insert(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
TypeError: insert expected 2 arguments, got 1
[2025-01-22T12:22:37.258+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2025-01-22T12:22:37.315+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/reddit_dag.py took 0.111 seconds
[2025-01-22T12:23:07.924+0000] {processor.py:186} INFO - Started process (PID=34) to work on /opt/airflow/dags/reddit_dag.py
[2025-01-22T12:23:07.933+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2025-01-22T12:23:07.989+0000] {logging_mixin.py:190} INFO - [2025-01-22T12:23:07.978+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2025-01-22T12:23:08.077+0000] {logging_mixin.py:190} INFO - [2025-01-22T12:23:08.056+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 7, in <module>
    sys.path.insert(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
TypeError: insert expected 2 arguments, got 1
[2025-01-22T12:23:08.083+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2025-01-22T12:23:08.770+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/reddit_dag.py took 0.983 seconds
[2025-01-22T12:23:41.034+0000] {processor.py:186} INFO - Started process (PID=35) to work on /opt/airflow/dags/reddit_dag.py
[2025-01-22T12:23:41.036+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2025-01-22T12:23:41.060+0000] {logging_mixin.py:190} INFO - [2025-01-22T12:23:41.054+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2025-01-22T12:23:41.095+0000] {logging_mixin.py:190} INFO - [2025-01-22T12:23:41.087+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 7, in <module>
    sys.path.insert(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
TypeError: insert expected 2 arguments, got 1
[2025-01-22T12:23:41.096+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2025-01-22T12:23:41.180+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/reddit_dag.py took 0.172 seconds
[2025-01-22T12:24:11.428+0000] {processor.py:186} INFO - Started process (PID=36) to work on /opt/airflow/dags/reddit_dag.py
[2025-01-22T12:24:11.431+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2025-01-22T12:24:11.440+0000] {logging_mixin.py:190} INFO - [2025-01-22T12:24:11.439+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2025-01-22T12:24:11.452+0000] {logging_mixin.py:190} INFO - [2025-01-22T12:24:11.448+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 7, in <module>
    sys.path.insert(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
TypeError: insert expected 2 arguments, got 1
[2025-01-22T12:24:11.454+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2025-01-22T12:24:11.506+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/reddit_dag.py took 0.094 seconds
[2025-01-22T12:24:41.899+0000] {processor.py:186} INFO - Started process (PID=37) to work on /opt/airflow/dags/reddit_dag.py
[2025-01-22T12:24:41.903+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2025-01-22T12:24:41.919+0000] {logging_mixin.py:190} INFO - [2025-01-22T12:24:41.916+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2025-01-22T12:24:41.939+0000] {logging_mixin.py:190} INFO - [2025-01-22T12:24:41.934+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 7, in <module>
    sys.path.insert(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
TypeError: insert expected 2 arguments, got 1
[2025-01-22T12:24:41.942+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2025-01-22T12:24:42.011+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/reddit_dag.py took 0.145 seconds
[2025-01-22T12:26:25.792+0000] {processor.py:186} INFO - Started process (PID=33) to work on /opt/airflow/dags/reddit_dag.py
[2025-01-22T12:26:25.796+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2025-01-22T12:26:25.805+0000] {logging_mixin.py:190} INFO - [2025-01-22T12:26:25.803+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2025-01-22T12:26:25.823+0000] {logging_mixin.py:190} INFO - [2025-01-22T12:26:25.819+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 7, in <module>
    sys.path.insert(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
TypeError: insert expected 2 arguments, got 1
[2025-01-22T12:26:25.826+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2025-01-22T12:26:25.884+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/reddit_dag.py took 0.109 seconds
[2025-01-22T12:26:56.716+0000] {processor.py:186} INFO - Started process (PID=34) to work on /opt/airflow/dags/reddit_dag.py
[2025-01-22T12:26:56.723+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2025-01-22T12:26:56.785+0000] {logging_mixin.py:190} INFO - [2025-01-22T12:26:56.777+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2025-01-22T12:26:56.863+0000] {logging_mixin.py:190} INFO - [2025-01-22T12:26:56.846+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 7, in <module>
    sys.path.insert(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
TypeError: insert expected 2 arguments, got 1
[2025-01-22T12:26:56.866+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2025-01-22T12:26:57.498+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/reddit_dag.py took 0.922 seconds
[2025-01-22T12:27:27.825+0000] {processor.py:186} INFO - Started process (PID=35) to work on /opt/airflow/dags/reddit_dag.py
[2025-01-22T12:27:27.842+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2025-01-22T12:27:27.931+0000] {logging_mixin.py:190} INFO - [2025-01-22T12:27:27.898+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2025-01-22T12:27:29.774+0000] {logging_mixin.py:190} INFO - [2025-01-22T12:27:28.178+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 7, in <module>
    sys.path.insert(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
TypeError: insert expected 2 arguments, got 1
[2025-01-22T12:27:30.239+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2025-01-22T12:27:51.466+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/reddit_dag.py took 24.272 seconds
[2025-01-22T12:28:22.269+0000] {processor.py:186} INFO - Started process (PID=36) to work on /opt/airflow/dags/reddit_dag.py
[2025-01-22T12:28:22.274+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2025-01-22T12:28:22.334+0000] {logging_mixin.py:190} INFO - [2025-01-22T12:28:22.324+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2025-01-22T12:28:22.406+0000] {logging_mixin.py:190} INFO - [2025-01-22T12:28:22.389+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 7, in <module>
    sys.path.insert(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
TypeError: insert expected 2 arguments, got 1
[2025-01-22T12:28:22.411+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2025-01-22T12:28:22.587+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/reddit_dag.py took 0.412 seconds
[2025-01-22T12:28:52.976+0000] {processor.py:186} INFO - Started process (PID=37) to work on /opt/airflow/dags/reddit_dag.py
[2025-01-22T12:28:52.981+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2025-01-22T12:28:52.990+0000] {logging_mixin.py:190} INFO - [2025-01-22T12:28:52.989+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2025-01-22T12:28:53.004+0000] {logging_mixin.py:190} INFO - [2025-01-22T12:28:53.000+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 7, in <module>
    sys.path.insert(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
TypeError: insert expected 2 arguments, got 1
[2025-01-22T12:28:53.007+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2025-01-22T12:28:53.087+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/reddit_dag.py took 0.131 seconds
[2025-01-22T12:29:48.412+0000] {processor.py:186} INFO - Started process (PID=38) to work on /opt/airflow/dags/reddit_dag.py
[2025-01-22T12:29:48.418+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2025-01-22T12:29:48.440+0000] {logging_mixin.py:190} INFO - [2025-01-22T12:29:48.435+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2025-01-22T12:29:48.519+0000] {logging_mixin.py:190} INFO - [2025-01-22T12:29:48.490+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 7, in <module>
    sys.path.insert(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
TypeError: insert expected 2 arguments, got 1
[2025-01-22T12:29:48.526+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2025-01-22T12:29:48.661+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/reddit_dag.py took 0.321 seconds
[2025-01-22T12:30:18.907+0000] {processor.py:186} INFO - Started process (PID=39) to work on /opt/airflow/dags/reddit_dag.py
[2025-01-22T12:30:18.909+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2025-01-22T12:30:18.918+0000] {logging_mixin.py:190} INFO - [2025-01-22T12:30:18.917+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2025-01-22T12:30:18.931+0000] {logging_mixin.py:190} INFO - [2025-01-22T12:30:18.927+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 7, in <module>
    sys.path.insert(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
TypeError: insert expected 2 arguments, got 1
[2025-01-22T12:30:18.933+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2025-01-22T12:30:18.987+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/reddit_dag.py took 0.098 seconds
[2025-01-22T12:30:49.276+0000] {processor.py:186} INFO - Started process (PID=40) to work on /opt/airflow/dags/reddit_dag.py
[2025-01-22T12:30:49.279+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2025-01-22T12:30:49.288+0000] {logging_mixin.py:190} INFO - [2025-01-22T12:30:49.287+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2025-01-22T12:30:49.303+0000] {logging_mixin.py:190} INFO - [2025-01-22T12:30:49.298+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 7, in <module>
    sys.path.insert(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
TypeError: insert expected 2 arguments, got 1
[2025-01-22T12:30:49.306+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2025-01-22T12:30:49.372+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/reddit_dag.py took 0.116 seconds
[2025-01-22T12:31:19.807+0000] {processor.py:186} INFO - Started process (PID=41) to work on /opt/airflow/dags/reddit_dag.py
[2025-01-22T12:31:19.810+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2025-01-22T12:31:19.821+0000] {logging_mixin.py:190} INFO - [2025-01-22T12:31:19.818+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2025-01-22T12:31:19.872+0000] {logging_mixin.py:190} INFO - [2025-01-22T12:31:19.852+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 7, in <module>
    sys.path.insert(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
TypeError: insert expected 2 arguments, got 1
[2025-01-22T12:31:19.877+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2025-01-22T12:31:20.044+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/reddit_dag.py took 0.262 seconds
[2025-01-22T12:32:39.573+0000] {processor.py:186} INFO - Started process (PID=42) to work on /opt/airflow/dags/reddit_dag.py
[2025-01-22T12:32:39.579+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2025-01-22T12:32:39.652+0000] {logging_mixin.py:190} INFO - [2025-01-22T12:32:39.643+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2025-01-22T12:32:39.680+0000] {logging_mixin.py:190} INFO - [2025-01-22T12:32:39.669+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 7, in <module>
    sys.path.insert(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
TypeError: insert expected 2 arguments, got 1
[2025-01-22T12:32:39.683+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2025-01-22T12:32:39.773+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/reddit_dag.py took 0.456 seconds
[2025-01-22T12:33:10.198+0000] {processor.py:186} INFO - Started process (PID=43) to work on /opt/airflow/dags/reddit_dag.py
[2025-01-22T12:33:10.200+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2025-01-22T12:33:10.208+0000] {logging_mixin.py:190} INFO - [2025-01-22T12:33:10.207+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2025-01-22T12:33:10.220+0000] {logging_mixin.py:190} INFO - [2025-01-22T12:33:10.215+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 7, in <module>
    sys.path.insert(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
TypeError: insert expected 2 arguments, got 1
[2025-01-22T12:33:10.221+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2025-01-22T12:33:10.276+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/reddit_dag.py took 0.094 seconds
[2025-01-22T12:33:40.684+0000] {processor.py:186} INFO - Started process (PID=44) to work on /opt/airflow/dags/reddit_dag.py
[2025-01-22T12:33:40.696+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2025-01-22T12:33:40.720+0000] {logging_mixin.py:190} INFO - [2025-01-22T12:33:40.714+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2025-01-22T12:33:40.771+0000] {logging_mixin.py:190} INFO - [2025-01-22T12:33:40.754+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 7, in <module>
    sys.path.insert(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
TypeError: insert expected 2 arguments, got 1
[2025-01-22T12:33:40.781+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2025-01-22T12:33:41.109+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/reddit_dag.py took 0.482 seconds
[2025-01-22T12:34:20.366+0000] {processor.py:186} INFO - Started process (PID=45) to work on /opt/airflow/dags/reddit_dag.py
[2025-01-22T12:34:20.368+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2025-01-22T12:34:20.382+0000] {logging_mixin.py:190} INFO - [2025-01-22T12:34:20.379+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2025-01-22T12:34:20.411+0000] {logging_mixin.py:190} INFO - [2025-01-22T12:34:20.400+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 7, in <module>
    sys.path.insert(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
TypeError: insert expected 2 arguments, got 1
[2025-01-22T12:34:20.414+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2025-01-22T12:34:20.533+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/reddit_dag.py took 0.206 seconds
[2025-01-22T12:34:50.902+0000] {processor.py:186} INFO - Started process (PID=46) to work on /opt/airflow/dags/reddit_dag.py
[2025-01-22T12:34:50.905+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2025-01-22T12:34:50.913+0000] {logging_mixin.py:190} INFO - [2025-01-22T12:34:50.912+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2025-01-22T12:34:50.927+0000] {logging_mixin.py:190} INFO - [2025-01-22T12:34:50.922+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 7, in <module>
    sys.path.insert(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
TypeError: insert expected 2 arguments, got 1
[2025-01-22T12:34:50.929+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2025-01-22T12:34:50.982+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/reddit_dag.py took 0.098 seconds
[2025-01-22T12:35:21.245+0000] {processor.py:186} INFO - Started process (PID=47) to work on /opt/airflow/dags/reddit_dag.py
[2025-01-22T12:35:21.249+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2025-01-22T12:35:21.260+0000] {logging_mixin.py:190} INFO - [2025-01-22T12:35:21.258+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2025-01-22T12:35:21.275+0000] {logging_mixin.py:190} INFO - [2025-01-22T12:35:21.271+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 7, in <module>
    sys.path.insert(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
TypeError: insert expected 2 arguments, got 1
[2025-01-22T12:35:21.278+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2025-01-22T12:35:21.345+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/reddit_dag.py took 0.121 seconds
[2025-01-22T12:35:51.662+0000] {processor.py:186} INFO - Started process (PID=48) to work on /opt/airflow/dags/reddit_dag.py
[2025-01-22T12:35:51.664+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2025-01-22T12:35:51.674+0000] {logging_mixin.py:190} INFO - [2025-01-22T12:35:51.672+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2025-01-22T12:35:51.686+0000] {logging_mixin.py:190} INFO - [2025-01-22T12:35:51.682+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 7, in <module>
    sys.path.insert(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
TypeError: insert expected 2 arguments, got 1
[2025-01-22T12:35:51.688+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2025-01-22T12:35:51.742+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/reddit_dag.py took 0.100 seconds
[2025-01-22T12:38:11.944+0000] {processor.py:186} INFO - Started process (PID=49) to work on /opt/airflow/dags/reddit_dag.py
[2025-01-22T12:38:11.947+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2025-01-22T12:38:11.961+0000] {logging_mixin.py:190} INFO - [2025-01-22T12:38:11.957+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2025-01-22T12:38:11.990+0000] {logging_mixin.py:190} INFO - [2025-01-22T12:38:11.974+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 7, in <module>
    sys.path.insert(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
TypeError: insert expected 2 arguments, got 1
[2025-01-22T12:38:11.992+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2025-01-22T12:38:12.551+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/reddit_dag.py took 0.651 seconds
[2025-01-22T12:38:43.066+0000] {processor.py:186} INFO - Started process (PID=50) to work on /opt/airflow/dags/reddit_dag.py
[2025-01-22T12:38:43.073+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2025-01-22T12:38:43.106+0000] {logging_mixin.py:190} INFO - [2025-01-22T12:38:43.104+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2025-01-22T12:38:43.162+0000] {logging_mixin.py:190} INFO - [2025-01-22T12:38:43.143+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 7, in <module>
    sys.path.insert(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
TypeError: insert expected 2 arguments, got 1
[2025-01-22T12:38:43.170+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2025-01-22T12:38:43.399+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/reddit_dag.py took 0.392 seconds
[2025-01-22T12:39:31.706+0000] {processor.py:186} INFO - Started process (PID=51) to work on /opt/airflow/dags/reddit_dag.py
[2025-01-22T12:39:31.716+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2025-01-22T12:39:31.736+0000] {logging_mixin.py:190} INFO - [2025-01-22T12:39:31.732+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2025-01-22T12:39:31.853+0000] {logging_mixin.py:190} INFO - [2025-01-22T12:39:31.836+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 7, in <module>
    sys.path.insert(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
TypeError: insert expected 2 arguments, got 1
[2025-01-22T12:39:31.857+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2025-01-22T12:39:32.056+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/reddit_dag.py took 12.911 seconds
[2025-01-22T12:41:50.022+0000] {processor.py:186} INFO - Started process (PID=33) to work on /opt/airflow/dags/reddit_dag.py
[2025-01-22T12:41:50.029+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2025-01-22T12:41:50.043+0000] {logging_mixin.py:190} INFO - [2025-01-22T12:41:50.041+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2025-01-22T12:41:50.065+0000] {logging_mixin.py:190} INFO - [2025-01-22T12:41:50.058+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 7, in <module>
    sys.path.insert(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
TypeError: insert expected 2 arguments, got 1
[2025-01-22T12:41:50.068+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2025-01-22T12:41:50.153+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/reddit_dag.py took 0.164 seconds
[2025-01-22T12:43:59.552+0000] {processor.py:186} INFO - Started process (PID=33) to work on /opt/airflow/dags/reddit_dag.py
[2025-01-22T12:43:59.556+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2025-01-22T12:43:59.569+0000] {logging_mixin.py:190} INFO - [2025-01-22T12:43:59.567+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2025-01-22T12:43:59.591+0000] {logging_mixin.py:190} INFO - [2025-01-22T12:43:59.586+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 7, in <module>
    sys.path.insert(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
TypeError: insert expected 2 arguments, got 1
[2025-01-22T12:43:59.594+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2025-01-22T12:43:59.666+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/reddit_dag.py took 0.138 seconds
[2025-01-22T12:52:09.646+0000] {processor.py:186} INFO - Started process (PID=32) to work on /opt/airflow/dags/reddit_dag.py
[2025-01-22T12:52:09.650+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2025-01-22T12:52:09.657+0000] {logging_mixin.py:190} INFO - [2025-01-22T12:52:09.656+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2025-01-22T12:52:09.669+0000] {logging_mixin.py:190} INFO - [2025-01-22T12:52:09.665+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 7, in <module>
    sys.path.insert(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
TypeError: insert expected 2 arguments, got 1
[2025-01-22T12:52:09.672+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2025-01-22T12:52:09.730+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/reddit_dag.py took 0.099 seconds
[2025-01-22T12:52:40.362+0000] {processor.py:186} INFO - Started process (PID=33) to work on /opt/airflow/dags/reddit_dag.py
[2025-01-22T12:52:40.368+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2025-01-22T12:52:40.436+0000] {logging_mixin.py:190} INFO - [2025-01-22T12:52:40.427+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2025-01-22T12:52:40.524+0000] {logging_mixin.py:190} INFO - [2025-01-22T12:52:40.506+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 7, in <module>
    sys.path.insert(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
TypeError: insert expected 2 arguments, got 1
[2025-01-22T12:52:40.530+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2025-01-22T12:52:40.808+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/reddit_dag.py took 0.597 seconds
[2025-01-22T12:54:21.989+0000] {processor.py:186} INFO - Started process (PID=34) to work on /opt/airflow/dags/reddit_dag.py
[2025-01-22T12:54:22.003+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2025-01-22T12:54:22.162+0000] {logging_mixin.py:190} INFO - [2025-01-22T12:54:22.140+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2025-01-22T12:54:22.407+0000] {logging_mixin.py:190} INFO - [2025-01-22T12:54:22.360+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 7, in <module>
    sys.path.insert(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
TypeError: insert expected 2 arguments, got 1
[2025-01-22T12:54:22.419+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2025-01-22T12:54:23.783+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/reddit_dag.py took 27.686 seconds
[2025-01-22T12:54:55.196+0000] {processor.py:186} INFO - Started process (PID=35) to work on /opt/airflow/dags/reddit_dag.py
[2025-01-22T12:54:55.201+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2025-01-22T12:54:55.238+0000] {logging_mixin.py:190} INFO - [2025-01-22T12:54:55.230+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2025-01-22T12:54:55.323+0000] {logging_mixin.py:190} INFO - [2025-01-22T12:54:55.304+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 7, in <module>
    sys.path.insert(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
TypeError: insert expected 2 arguments, got 1
[2025-01-22T12:54:55.327+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2025-01-22T12:54:55.444+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/reddit_dag.py took 0.373 seconds
[2025-01-22T12:55:25.808+0000] {processor.py:186} INFO - Started process (PID=36) to work on /opt/airflow/dags/reddit_dag.py
[2025-01-22T12:55:25.811+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2025-01-22T12:55:25.820+0000] {logging_mixin.py:190} INFO - [2025-01-22T12:55:25.819+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2025-01-22T12:55:25.834+0000] {logging_mixin.py:190} INFO - [2025-01-22T12:55:25.829+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 7, in <module>
    sys.path.insert(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
TypeError: insert expected 2 arguments, got 1
[2025-01-22T12:55:25.836+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2025-01-22T12:55:25.891+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/reddit_dag.py took 0.100 seconds
[2025-01-22T12:55:56.214+0000] {processor.py:186} INFO - Started process (PID=37) to work on /opt/airflow/dags/reddit_dag.py
[2025-01-22T12:55:56.217+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2025-01-22T12:55:56.229+0000] {logging_mixin.py:190} INFO - [2025-01-22T12:55:56.228+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2025-01-22T12:55:56.242+0000] {logging_mixin.py:190} INFO - [2025-01-22T12:55:56.238+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 7, in <module>
    sys.path.insert(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
TypeError: insert expected 2 arguments, got 1
[2025-01-22T12:55:56.244+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2025-01-22T12:55:56.301+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/reddit_dag.py took 0.107 seconds
[2025-01-22T12:56:26.641+0000] {processor.py:186} INFO - Started process (PID=38) to work on /opt/airflow/dags/reddit_dag.py
[2025-01-22T12:56:26.646+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2025-01-22T12:56:26.667+0000] {logging_mixin.py:190} INFO - [2025-01-22T12:56:26.663+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2025-01-22T12:56:26.686+0000] {logging_mixin.py:190} INFO - [2025-01-22T12:56:26.681+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 7, in <module>
    sys.path.insert(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
TypeError: insert expected 2 arguments, got 1
[2025-01-22T12:56:26.690+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2025-01-22T12:56:26.750+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/reddit_dag.py took 0.138 seconds
[2025-01-22T12:56:57.093+0000] {processor.py:186} INFO - Started process (PID=39) to work on /opt/airflow/dags/reddit_dag.py
[2025-01-22T12:56:57.096+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2025-01-22T12:56:57.134+0000] {logging_mixin.py:190} INFO - [2025-01-22T12:56:57.131+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2025-01-22T12:56:57.157+0000] {logging_mixin.py:190} INFO - [2025-01-22T12:56:57.150+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 7, in <module>
    sys.path.insert(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
TypeError: insert expected 2 arguments, got 1
[2025-01-22T12:56:57.159+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2025-01-22T12:56:57.290+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/reddit_dag.py took 0.241 seconds
[2025-01-22T12:57:28.758+0000] {processor.py:186} INFO - Started process (PID=40) to work on /opt/airflow/dags/reddit_dag.py
[2025-01-22T12:57:28.804+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2025-01-22T12:57:31.170+0000] {logging_mixin.py:190} INFO - [2025-01-22T12:57:30.485+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2025-01-22T12:58:26.952+0000] {logging_mixin.py:190} INFO - [2025-01-22T12:58:23.812+0000] {timeout.py:68} ERROR - Process timed out, PID: 40
[2025-01-22T12:58:58.072+0000] {processor.py:186} INFO - Started process (PID=41) to work on /opt/airflow/dags/reddit_dag.py
[2025-01-22T12:58:58.074+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2025-01-22T12:58:58.086+0000] {logging_mixin.py:190} INFO - [2025-01-22T12:58:58.084+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2025-01-22T12:58:58.109+0000] {logging_mixin.py:190} INFO - [2025-01-22T12:58:58.105+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 7, in <module>
    sys.path.insert(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
TypeError: insert expected 2 arguments, got 1
[2025-01-22T12:58:58.112+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2025-01-22T12:58:58.220+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/reddit_dag.py took 0.176 seconds
[2025-01-22T12:59:28.399+0000] {processor.py:186} INFO - Started process (PID=42) to work on /opt/airflow/dags/reddit_dag.py
[2025-01-22T12:59:28.401+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2025-01-22T12:59:28.408+0000] {logging_mixin.py:190} INFO - [2025-01-22T12:59:28.407+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2025-01-22T12:59:28.423+0000] {logging_mixin.py:190} INFO - [2025-01-22T12:59:28.420+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 7, in <module>
    sys.path.insert(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
TypeError: insert expected 2 arguments, got 1
[2025-01-22T12:59:28.425+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2025-01-22T12:59:28.484+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/reddit_dag.py took 0.100 seconds
[2025-01-22T13:03:31.157+0000] {processor.py:186} INFO - Started process (PID=43) to work on /opt/airflow/dags/reddit_dag.py
[2025-01-22T13:03:31.169+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2025-01-22T13:03:31.333+0000] {logging_mixin.py:190} INFO - [2025-01-22T13:03:31.305+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2025-01-22T13:04:02.013+0000] {processor.py:186} INFO - Started process (PID=44) to work on /opt/airflow/dags/reddit_dag.py
[2025-01-22T13:04:02.016+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2025-01-22T13:04:02.025+0000] {logging_mixin.py:190} INFO - [2025-01-22T13:04:02.024+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2025-01-22T13:04:02.058+0000] {logging_mixin.py:190} INFO - [2025-01-22T13:04:02.035+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 7, in <module>
    sys.path.insert(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
TypeError: insert expected 2 arguments, got 1
[2025-01-22T13:04:02.062+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2025-01-22T13:04:02.216+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/reddit_dag.py took 0.224 seconds
[2025-01-22T13:04:33.058+0000] {processor.py:186} INFO - Started process (PID=45) to work on /opt/airflow/dags/reddit_dag.py
[2025-01-22T13:04:33.063+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2025-01-22T13:04:33.073+0000] {logging_mixin.py:190} INFO - [2025-01-22T13:04:33.071+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2025-01-22T13:04:33.101+0000] {logging_mixin.py:190} INFO - [2025-01-22T13:04:33.094+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 7, in <module>
    sys.path.insert(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
TypeError: insert expected 2 arguments, got 1
[2025-01-22T13:04:33.106+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2025-01-22T13:04:33.177+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/reddit_dag.py took 0.149 seconds
[2025-01-22T13:05:03.631+0000] {processor.py:186} INFO - Started process (PID=46) to work on /opt/airflow/dags/reddit_dag.py
[2025-01-22T13:05:03.635+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2025-01-22T13:05:03.646+0000] {logging_mixin.py:190} INFO - [2025-01-22T13:05:03.645+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2025-01-22T13:05:03.671+0000] {logging_mixin.py:190} INFO - [2025-01-22T13:05:03.666+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 7, in <module>
    sys.path.insert(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
TypeError: insert expected 2 arguments, got 1
[2025-01-22T13:05:03.674+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2025-01-22T13:05:03.739+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/reddit_dag.py took 0.135 seconds
[2025-01-22T13:05:34.075+0000] {processor.py:186} INFO - Started process (PID=47) to work on /opt/airflow/dags/reddit_dag.py
[2025-01-22T13:05:34.079+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2025-01-22T13:05:34.096+0000] {logging_mixin.py:190} INFO - [2025-01-22T13:05:34.094+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2025-01-22T13:05:34.121+0000] {logging_mixin.py:190} INFO - [2025-01-22T13:05:34.112+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 7, in <module>
    sys.path.insert(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
TypeError: insert expected 2 arguments, got 1
[2025-01-22T13:05:34.124+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2025-01-22T13:05:34.221+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/reddit_dag.py took 0.174 seconds
[2025-01-22T13:06:04.464+0000] {processor.py:186} INFO - Started process (PID=48) to work on /opt/airflow/dags/reddit_dag.py
[2025-01-22T13:06:04.467+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2025-01-22T13:06:04.477+0000] {logging_mixin.py:190} INFO - [2025-01-22T13:06:04.476+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2025-01-22T13:06:04.492+0000] {logging_mixin.py:190} INFO - [2025-01-22T13:06:04.489+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 7, in <module>
    sys.path.insert(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
TypeError: insert expected 2 arguments, got 1
[2025-01-22T13:06:04.495+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2025-01-22T13:06:04.561+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/reddit_dag.py took 0.115 seconds
[2025-01-22T13:06:34.938+0000] {processor.py:186} INFO - Started process (PID=49) to work on /opt/airflow/dags/reddit_dag.py
[2025-01-22T13:06:34.943+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2025-01-22T13:06:34.955+0000] {logging_mixin.py:190} INFO - [2025-01-22T13:06:34.953+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2025-01-22T13:06:34.974+0000] {logging_mixin.py:190} INFO - [2025-01-22T13:06:34.969+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 7, in <module>
    sys.path.insert(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
TypeError: insert expected 2 arguments, got 1
[2025-01-22T13:06:34.976+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2025-01-22T13:06:35.042+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/reddit_dag.py took 0.125 seconds
[2025-01-22T13:07:05.334+0000] {processor.py:186} INFO - Started process (PID=50) to work on /opt/airflow/dags/reddit_dag.py
[2025-01-22T13:07:05.337+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2025-01-22T13:07:05.344+0000] {logging_mixin.py:190} INFO - [2025-01-22T13:07:05.343+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2025-01-22T13:07:05.357+0000] {logging_mixin.py:190} INFO - [2025-01-22T13:07:05.353+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 7, in <module>
    sys.path.insert(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
TypeError: insert expected 2 arguments, got 1
[2025-01-22T13:07:05.359+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2025-01-22T13:07:05.420+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/reddit_dag.py took 0.106 seconds
[2025-01-22T13:07:35.744+0000] {processor.py:186} INFO - Started process (PID=51) to work on /opt/airflow/dags/reddit_dag.py
[2025-01-22T13:07:35.748+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2025-01-22T13:07:35.758+0000] {logging_mixin.py:190} INFO - [2025-01-22T13:07:35.757+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2025-01-22T13:07:35.775+0000] {logging_mixin.py:190} INFO - [2025-01-22T13:07:35.770+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 7, in <module>
    sys.path.insert(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
TypeError: insert expected 2 arguments, got 1
[2025-01-22T13:07:35.777+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2025-01-22T13:07:35.858+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/reddit_dag.py took 0.135 seconds
[2025-01-22T13:08:06.139+0000] {processor.py:186} INFO - Started process (PID=52) to work on /opt/airflow/dags/reddit_dag.py
[2025-01-22T13:08:06.142+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2025-01-22T13:08:06.153+0000] {logging_mixin.py:190} INFO - [2025-01-22T13:08:06.151+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2025-01-22T13:08:06.176+0000] {logging_mixin.py:190} INFO - [2025-01-22T13:08:06.170+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 7, in <module>
    sys.path.insert(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
TypeError: insert expected 2 arguments, got 1
[2025-01-22T13:08:06.179+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2025-01-22T13:08:06.246+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/reddit_dag.py took 0.129 seconds
[2025-01-22T13:08:36.754+0000] {processor.py:186} INFO - Started process (PID=53) to work on /opt/airflow/dags/reddit_dag.py
[2025-01-22T13:08:36.758+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2025-01-22T13:08:36.770+0000] {logging_mixin.py:190} INFO - [2025-01-22T13:08:36.768+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2025-01-22T13:08:36.789+0000] {logging_mixin.py:190} INFO - [2025-01-22T13:08:36.782+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 7, in <module>
    sys.path.insert(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
TypeError: insert expected 2 arguments, got 1
[2025-01-22T13:08:36.792+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2025-01-22T13:08:36.895+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/reddit_dag.py took 0.179 seconds
[2025-01-22T13:10:36.266+0000] {processor.py:186} INFO - Started process (PID=33) to work on /opt/airflow/dags/reddit_dag.py
[2025-01-22T13:10:36.272+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2025-01-22T13:10:36.283+0000] {logging_mixin.py:190} INFO - [2025-01-22T13:10:36.281+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2025-01-22T13:10:36.302+0000] {logging_mixin.py:190} INFO - [2025-01-22T13:10:36.297+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 7, in <module>
    sys.path.insert(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
TypeError: insert expected 2 arguments, got 1
[2025-01-22T13:10:36.305+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2025-01-22T13:10:36.386+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/reddit_dag.py took 0.154 seconds
[2025-01-22T13:13:27.804+0000] {processor.py:186} INFO - Started process (PID=33) to work on /opt/airflow/dags/reddit_dag.py
[2025-01-22T13:13:27.808+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2025-01-22T13:13:27.817+0000] {logging_mixin.py:190} INFO - [2025-01-22T13:13:27.815+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2025-01-22T13:13:27.833+0000] {logging_mixin.py:190} INFO - [2025-01-22T13:13:27.826+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 7, in <module>
    sys.path.insert(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
TypeError: insert expected 2 arguments, got 1
[2025-01-22T13:13:27.836+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2025-01-22T13:13:27.903+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/reddit_dag.py took 0.116 seconds
[2025-01-22T13:20:20.846+0000] {processor.py:186} INFO - Started process (PID=32) to work on /opt/airflow/dags/reddit_dag.py
[2025-01-22T13:20:20.850+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2025-01-22T13:20:20.861+0000] {logging_mixin.py:190} INFO - [2025-01-22T13:20:20.860+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2025-01-22T13:20:20.882+0000] {logging_mixin.py:190} INFO - [2025-01-22T13:20:20.876+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 7, in <module>
    sys.path.insert(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
TypeError: insert expected 2 arguments, got 1
[2025-01-22T13:20:20.885+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2025-01-22T13:20:20.951+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/reddit_dag.py took 0.131 seconds
[2025-01-22T13:20:51.659+0000] {processor.py:186} INFO - Started process (PID=33) to work on /opt/airflow/dags/reddit_dag.py
[2025-01-22T13:20:51.669+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2025-01-22T13:20:51.761+0000] {logging_mixin.py:190} INFO - [2025-01-22T13:20:51.751+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2025-01-22T13:20:51.854+0000] {logging_mixin.py:190} INFO - [2025-01-22T13:20:51.838+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 7, in <module>
    sys.path.insert(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
TypeError: insert expected 2 arguments, got 1
[2025-01-22T13:20:51.860+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2025-01-22T13:20:52.139+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/reddit_dag.py took 0.645 seconds
[2025-01-22T13:21:23.129+0000] {processor.py:186} INFO - Started process (PID=34) to work on /opt/airflow/dags/reddit_dag.py
[2025-01-22T13:21:23.140+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2025-01-22T13:21:23.192+0000] {logging_mixin.py:190} INFO - [2025-01-22T13:21:23.173+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2025-01-22T13:21:23.349+0000] {logging_mixin.py:190} INFO - [2025-01-22T13:21:23.304+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 7, in <module>
    sys.path.insert(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
TypeError: insert expected 2 arguments, got 1
[2025-01-22T13:21:23.367+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2025-01-22T13:21:23.864+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/reddit_dag.py took 0.811 seconds
[2025-01-22T13:22:19.812+0000] {processor.py:186} INFO - Started process (PID=35) to work on /opt/airflow/dags/reddit_dag.py
[2025-01-22T13:22:19.929+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2025-01-22T13:22:20.629+0000] {logging_mixin.py:190} INFO - [2025-01-22T13:22:20.460+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2025-01-22T13:22:23.903+0000] {logging_mixin.py:190} INFO - [2025-01-22T13:22:23.565+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 7, in <module>
    sys.path.insert(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
TypeError: insert expected 2 arguments, got 1
[2025-01-22T13:22:25.449+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2025-01-22T13:22:26.326+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/reddit_dag.py took 10.251 seconds
[2025-01-22T13:22:57.243+0000] {processor.py:186} INFO - Started process (PID=36) to work on /opt/airflow/dags/reddit_dag.py
[2025-01-22T13:22:57.247+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2025-01-22T13:22:57.279+0000] {logging_mixin.py:190} INFO - [2025-01-22T13:22:57.272+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2025-01-22T13:22:57.333+0000] {logging_mixin.py:190} INFO - [2025-01-22T13:22:57.319+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 7, in <module>
    sys.path.insert(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
TypeError: insert expected 2 arguments, got 1
[2025-01-22T13:22:57.335+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2025-01-22T13:22:57.448+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/reddit_dag.py took 0.255 seconds
[2025-01-22T13:23:27.786+0000] {processor.py:186} INFO - Started process (PID=37) to work on /opt/airflow/dags/reddit_dag.py
[2025-01-22T13:23:27.796+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2025-01-22T13:23:27.807+0000] {logging_mixin.py:190} INFO - [2025-01-22T13:23:27.806+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2025-01-22T13:23:27.839+0000] {logging_mixin.py:190} INFO - [2025-01-22T13:23:27.831+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 7, in <module>
    sys.path.insert(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
TypeError: insert expected 2 arguments, got 1
[2025-01-22T13:23:27.841+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2025-01-22T13:23:27.951+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/reddit_dag.py took 0.190 seconds
[2025-01-22T13:23:58.600+0000] {processor.py:186} INFO - Started process (PID=38) to work on /opt/airflow/dags/reddit_dag.py
[2025-01-22T13:23:58.636+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2025-01-22T13:23:58.650+0000] {logging_mixin.py:190} INFO - [2025-01-22T13:23:58.649+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2025-01-22T13:23:58.681+0000] {logging_mixin.py:190} INFO - [2025-01-22T13:23:58.672+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 7, in <module>
    sys.path.insert(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
TypeError: insert expected 2 arguments, got 1
[2025-01-22T13:23:58.685+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2025-01-22T13:23:58.789+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/reddit_dag.py took 0.217 seconds
[2025-01-22T13:24:29.124+0000] {processor.py:186} INFO - Started process (PID=39) to work on /opt/airflow/dags/reddit_dag.py
[2025-01-22T13:24:29.127+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2025-01-22T13:24:29.138+0000] {logging_mixin.py:190} INFO - [2025-01-22T13:24:29.136+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2025-01-22T13:24:29.152+0000] {logging_mixin.py:190} INFO - [2025-01-22T13:24:29.148+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 7, in <module>
    sys.path.insert(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
TypeError: insert expected 2 arguments, got 1
[2025-01-22T13:24:29.155+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2025-01-22T13:24:29.214+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/reddit_dag.py took 0.106 seconds
[2025-01-22T13:24:59.571+0000] {processor.py:186} INFO - Started process (PID=40) to work on /opt/airflow/dags/reddit_dag.py
[2025-01-22T13:24:59.577+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2025-01-22T13:24:59.625+0000] {logging_mixin.py:190} INFO - [2025-01-22T13:24:59.621+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2025-01-22T13:24:59.680+0000] {logging_mixin.py:190} INFO - [2025-01-22T13:24:59.671+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 7, in <module>
    sys.path.insert(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
TypeError: insert expected 2 arguments, got 1
[2025-01-22T13:24:59.685+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2025-01-22T13:24:59.893+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/reddit_dag.py took 0.445 seconds
[2025-01-22T13:26:58.740+0000] {processor.py:186} INFO - Started process (PID=41) to work on /opt/airflow/dags/reddit_dag.py
[2025-01-22T13:26:59.109+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2025-01-22T13:27:09.436+0000] {logging_mixin.py:190} INFO - [2025-01-22T13:27:07.711+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2025-01-22T13:27:48.484+0000] {logging_mixin.py:190} INFO - [2025-01-22T13:27:46.570+0000] {timeout.py:68} ERROR - Process timed out, PID: 41
[2025-01-22T13:29:09.556+0000] {processor.py:186} INFO - Started process (PID=42) to work on /opt/airflow/dags/reddit_dag.py
[2025-01-22T13:29:09.594+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2025-01-22T13:29:09.776+0000] {logging_mixin.py:190} INFO - [2025-01-22T13:29:09.754+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2025-01-22T13:29:09.971+0000] {logging_mixin.py:190} INFO - [2025-01-22T13:29:09.916+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 7, in <module>
    sys.path.insert(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
TypeError: insert expected 2 arguments, got 1
[2025-01-22T13:29:09.980+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2025-01-22T13:29:12.362+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/reddit_dag.py took 6.175 seconds
[2025-01-22T13:29:42.802+0000] {processor.py:186} INFO - Started process (PID=43) to work on /opt/airflow/dags/reddit_dag.py
[2025-01-22T13:29:42.806+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/reddit_dag.py for tasks to queue
[2025-01-22T13:29:42.818+0000] {logging_mixin.py:190} INFO - [2025-01-22T13:29:42.817+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/reddit_dag.py
[2025-01-22T13:29:42.834+0000] {logging_mixin.py:190} INFO - [2025-01-22T13:29:42.829+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/reddit_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/reddit_dag.py", line 7, in <module>
    sys.path.insert(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
TypeError: insert expected 2 arguments, got 1
[2025-01-22T13:29:42.837+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/reddit_dag.py
[2025-01-22T13:29:42.910+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/reddit_dag.py took 0.138 seconds
